#define PROG_NAME "Opentube"
#define PROG_VERSION "0.1alpha"
#define DEBUG_LEVEL 3 // 0 - disabled
#define SERVER_STRING PROG_NAME "/" PROG_VERSION
#define IPV6_SUPPORT 1
#define WORKER_THREADS 10
#define MAX_EVENTS 10
#define CONFIG_PATH "./server.conf"
#define LISTEN_BACKLOG 500
#define HTTP_BUFFER_RESERVED_SIZE 262144
#define HTTP_RECV_BUFFER 8192
#define HTTP_HEADERS_POOL_RESERVED_FRAGMENTS 32
#define HTTP_GZIP_BUFFER_RESERVED_SIZE 65536
#define HTTP_CLIENTS_POOL_RESERVED_SIZE 128
#define HTTP_BODY_SIZE_WRITE_TO_FILE 8388608 // 8 Mb
#define HTTP_MAX_REQUEST_BODY_SIZE 33554432 // 32 Mb
#define HTTP_MAX_HEADERS_SIZE 16384
#define HTTP_STATIC_EXPIRES 172800 // 2 days
#define HTTP_PATH_PREALLOC 128
#define EPOLL_TIMEOUT 2500

#define HAVE_ACCEPT4 1
